# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Sagar_Engineet.AI_Test' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire'
  pod 'UIScrollView-InfiniteScroll'
end
